#ifndef POKEPLATINUM_CONSTANTS_DEBUG_MENU_H
#define POKEPLATINUM_CONSTANTS_DEBUG_MENU_H

#include "generated/vars_flags.h"

#define DEBUG_MENU_ENABLED TRUE

#define DEBUG_COLOR_WHITE 15
#define DEBUG_COLOR_BLACK 11

#define DEBUG_KEY PAD_BUTTON_R

#define MAX_SUBMENU_DATA 8

#define FLAG_DEBUG_NO_COLLISION   FLAG_UNUSED_2420
#define FLAG_DEBUG_NO_TRAINER_SEE FLAG_UNUSED_2421
#define FLAG_DEBUG_NO_ENCOUNTERS  FLAG_UNUSED_2422
#define FLAG_DEBUG_GAME_START     FLAG_UNUSED_2448

#endif // POKEPLATINUM_CONSTANTS_DEBUG_MENU_H
